/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectutsnumtod;

import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Andreas Bayu P
 */
public class UIProject extends javax.swing.JFrame {

    MetodeDasar data;
    double akarX1, akarX2;
    int angkaSignifikan, maxLoop;
    DefaultTableModel mdl;

    /**
     * Creates new form UIProject
     */
    public UIProject() {
        initComponents();

        mdl = (DefaultTableModel) tableResult.getModel();

        setHeaderTable();
    }

    private void setHeaderTable() {
        JTableHeader hdr = tableResult.getTableHeader();
        Font fnt = new Font("Segoe UI", Font.PLAIN, 16);
        hdr.setFont(fnt);

        TableColumnModel clm = tableResult.getColumnModel();
        TableColumn col = clm.getColumn(0);
        col.setMaxWidth(80);
    }

    private void clearTextTable() {
        labelMetode.setText("");
        labelFin.setText("");
    }

    private void clearTable() {
        if (mdl.getRowCount() > 0) {
            for (int i = mdl.getRowCount() - 1; i >= 0; i--) {
                mdl.removeRow(i);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdoMetode = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdoTertutup = new javax.swing.JRadioButton();
        rdoTerbuka = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtAkarX1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAkarX2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAngkaSignifikan = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMaxLoop = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableResult = new javax.swing.JTable();
        labelMetode = new javax.swing.JLabel();
        labelFin = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menghitung Akar Persamaan");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("f(x) = sin(x) - e^x - x");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Pilih Metode : ");

        rdoMetode.add(rdoTertutup);
        rdoTertutup.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoTertutup.setText("Tertutup");
        rdoTertutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTertutupActionPerformed(evt);
            }
        });

        rdoMetode.add(rdoTerbuka);
        rdoTerbuka.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoTerbuka.setText("Terbuka");
        rdoTerbuka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoTerbukaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Akar X1 :");

        txtAkarX1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Akar X2 :");

        txtAkarX2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Angka Signifikan :");

        txtAngkaSignifikan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Maksimal Iterasi :");

        txtMaxLoop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tableResult.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Iterasi", "Nilai X", "Kesalahan Pendekatan Relatif"
            }
        ));
        tableResult.setEnabled(false);
        tableResult.setShowHorizontalLines(true);
        tableResult.setShowVerticalLines(true);
        jScrollPane1.setViewportView(tableResult);

        labelMetode.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        labelFin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnHitung.setBackground(new java.awt.Color(51, 255, 51));
        btnHitung.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(0, 0, 0));
        btnHitung.setText("HITUNG");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rdoTerbuka, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoTertutup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtMaxLoop, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAkarX1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAkarX2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAngkaSignifikan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFin, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMetode, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(270, 270, 270)
                    .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(864, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelMetode, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelFin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(59, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rdoTertutup)
                            .addComponent(rdoTerbuka))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAkarX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAkarX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtAngkaSignifikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMaxLoop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(310, Short.MAX_VALUE)
                    .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(91, 91, 91)))
        );

        setSize(new java.awt.Dimension(1230, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        txtAkarX1.setText("");
        txtAkarX2.setText("");
        txtAngkaSignifikan.setText("");
        txtMaxLoop.setText("");
        labelMetode.setText("");
        labelFin.setText("");
        txtAkarX1.setFocusable(true);
        clearTable();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void rdoTerbukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTerbukaActionPerformed
        // TODO add your handling code here:
        if (rdoTerbuka.isSelected()) {
            labelMetode.setText("Menggunakan Metode Newton Raphson");
            txtAkarX2.setEnabled(false);
        }
    }//GEN-LAST:event_rdoTerbukaActionPerformed

    private void rdoTertutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoTertutupActionPerformed
        // TODO add your handling code here:
        if (rdoTertutup.isSelected()) {
            labelMetode.setText("Menggunakan Metode Regula Falsi");
            txtAkarX2.setEnabled(true);
        }
    }//GEN-LAST:event_rdoTertutupActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        try {
            clearTable();

            akarX1 = Double.parseDouble(txtAkarX1.getText());
            angkaSignifikan = Integer.parseInt(txtAngkaSignifikan.getText());
            maxLoop = Integer.parseInt(txtMaxLoop.getText());

            if (akarX1 == akarX2) {
                JOptionPane.showMessageDialog(this, "Akar X1 dan X2 tidak boleh sama");
                clearTextTable();
            } else {
                if (rdoTerbuka.isSelected()) {
                    data = new MetodeTerbuka(akarX1, angkaSignifikan, maxLoop);
                } else {
                    akarX2 = Double.parseDouble(txtAkarX2.getText());
                    data = new MetodeTertutup(akarX1, akarX2, angkaSignifikan, maxLoop);
                }

                double epsilon_s = data.Hitung_epsilon_s();
                double epsilon_a;

                if (data instanceof MetodeTerbuka) {
                    double x_sebelum = 0;
                    double x_sekarang = data.getAkarX1();
                    epsilon_a = 0;
                    
                    for (int i = 0; i < data.getMaxLoop(); i++) {
                        if (i == 0) {
                            mdl.addRow(new Object[]{String.valueOf(i), String.valueOf(x_sekarang), "-"});
                            tableResult.setModel(mdl);
                            x_sebelum = x_sekarang;
                            continue;
                        } else {
                            x_sekarang = data.Hitung_x_sekarang(x_sebelum);
                            epsilon_a = data.Hitung_epsilon_a(x_sebelum, x_sekarang);
                            mdl.addRow(new Object[]{String.valueOf(i), String.valueOf(x_sekarang), String.format("%.20f", epsilon_a) + "%"});
                            x_sebelum = x_sekarang;
                        }

                        if (epsilon_a < epsilon_s) {
                            break;
                        }
                    }
                    labelFin.setText("Hasil pendekatan akar f(x) pada akar adalah " + x_sekarang);

                } else if (data instanceof MetodeTertutup) {
                    double x_lower, x_upper;
                    tableResult.setModel(new TableModel("1"));
                    if (data.Hitung_f_x(akarX1) * data.Hitung_f_x(akarX2) < 0) {
                        if (akarX1 > akarX2) {
                            x_lower = akarX2;
                            x_upper = akarX1;
                        } else {
                            x_lower = akarX1;
                            x_upper = akarX2;
                        }

                        double x_sebelum = 0;
                        double x_sekarang = 0;
                        epsilon_a = 0;

                        for (int i = 0; i < data.getMaxLoop(); i++) {
                            x_sekarang = data.Hitung_x_sekarang(x_lower, x_upper);
                            double f_x_sekarang = data.Hitung_f_x(x_sekarang);

                            if (f_x_sekarang == 0) {
                                break;
                            } else if (f_x_sekarang < 0) {
                                x_lower = x_sekarang;
                            } else {
                                x_upper = x_sekarang;
                            }

                            if (i == 0) {
                                x_sebelum = x_sekarang;
                                mdl.addRow(new Object[]{String.valueOf(i + 1), String.valueOf(x_sekarang), "-"});
                                tableResult.setModel(mdl);
                                continue;
                            } else {
                                epsilon_a = data.Hitung_epsilon_a(x_sebelum, x_sekarang);
                                mdl.addRow(new Object[]{String.valueOf(i + 1), String.valueOf(x_sekarang), String.format("%.20f", epsilon_a) + "%"});
                                tableResult.setModel(mdl);
                                x_sebelum = x_sekarang;
                            }

                            if (epsilon_a < epsilon_s) {
                                break;
                            }
                        }

                        labelFin.setText("Hasil pendekatan akar f(x) pada akar " + akarX1 + " dan " + akarX2 + " adalah " + x_sekarang);
                    } else {
                        JOptionPane.showMessageDialog(this, "Hasil akar x1 dan x2 memiliki tanda yang sama.\nSilahkan ganti akar x1 dan x2 sehingga tandanya berbeda.");
                        clearTextTable();
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UIProject.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UIProject.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UIProject.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UIProject.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UIProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelFin;
    private javax.swing.JLabel labelMetode;
    private javax.swing.ButtonGroup rdoMetode;
    private javax.swing.JRadioButton rdoTerbuka;
    private javax.swing.JRadioButton rdoTertutup;
    private javax.swing.JTable tableResult;
    private javax.swing.JTextField txtAkarX1;
    private javax.swing.JTextField txtAkarX2;
    private javax.swing.JTextField txtAngkaSignifikan;
    private javax.swing.JTextField txtMaxLoop;
    // End of variables declaration//GEN-END:variables
}
